// src/main/webapp/entries/common-files/appbaseVue/src/App.vue
<template>
<div id="container"
	class="effect aside-float aside-bright navbar-fixed mainnav-fixed aside-fixed print-content mainnav-lg">
	<app-header> </app-header>
	<div class="boxed">
		<div id="content-container">
			<div class="main-content">
				<router-view></router-view>
			</div>
		</div>
		<app-sidebar> </app-sidebar>
	</div>
</div>
</template>

<script>
import Vue from "vue";
import Sidebar from "@/components/layout/Sidebar.vue";
import Header from "@/components/layout/Header.vue";

Vue.component("app-header", Header);
Vue.component("app-sidebar", Sidebar);

export default {
  name: "App"  
};
</script>

<style>
@import "/assets/css/app.css";
</style>

// src/main/webapp/entries/templates/nifty/react-files/web/app/App.js

import { HashRouter } from "react-router-dom";

import React from 'react';
import Root from './router/Root';
import Header from './components/layout/Header';
import Sidebar from './components/layout/Sidebar';

import './assets/css/custom.css';

export default class App extends React.Component {
  render() {
    return (
      <HashRouter>
        <div id="container" className="effect aside-float aside-bright navbar-fixed mainnav-fixed aside-fixed print-content mainnav-lg">
          <Header />
          <div className="boxed">
            <div id="content-container">
              <div className="main-content">
                <Root />
              </div>
            </div>
            <Sidebar />
          </div>
        </div>
      </HashRouter>
    )
  }
}
