// src/main/webapp/entries/common-files/appbaseVue/src/components/layout/Header.vue
<template>
<header id="navbar">
	<div id="navbar-container" class="boxed">
		<!--Brand logo & name-->
 		<!--================================-->
        <div class="navbar-header">
			<a href="" class="navbar-brand no-print">
				<img :src="'/static/images/logo.png'" alt="Nifty Logo" class="brand-icon">
				<div class="brand-title">
					<span class="brand-text">appAdmin</span>
				</div>
			</a>
		</div>
		<div class="navbar-content clearfix no-print">
			<ul class="nav navbar-top-links pull-left">
				<li class="tgl-menu-btn">
					<a class="mainnav-toggle" href="#">
						<i class="demo-pli-view-list"></i>
					</a>
				</li>
				<li class="mega-dropdown">
					<a href="#" class="mega-dropdown-toggle">
						<i class="demo-pli-layout-grid"></i>
					</a>
					<div class="dropdown-menu mega-dropdown-menu"></div>
				</li>
			</ul>
			<span class="main-header"> </span>
			<ul class="nav navbar-top-links pull-right">
				<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
				<li id="dropdown-user" class="dropdown">
					<a href="#" data-toggle="dropdown" class="dropdown-toggle text-right">
						<span class="pull-right">
							<i class="fa fa-user-o ic-user"></i>
						</span>
						<div class="index-username hidden-xs">chico</div>
					</a>
					<div class="dropdown-menu dropdown-menu-md dropdown-menu-right panel-default">
						<!-- Dropdown heading  -->
						<br>
						<!-- User dropdown menu -->
						<ul class="head-list">
							<li>
								<a href="javascript:void(-1)">
									<i class="fa fa-user-o icon-lg icon-fw"></i>
									Meus Dados
								</a>
							</li>
							<li>
								<a href="javascript:void(-1)">
									<i class="fa fa-info-circle icon-lg icon-fw"></i>
									Ajuda
								</a>
							</li>
						</ul>
						<!-- Dropdown footer -->
						<div class="pad-all text-right">
							<a href="j_spring_security_logout" class="btn btn-primary">
								<i class="fa fa-sign-out"></i>
								Sair
							</a>
						</div>
					</div>
				</li>
				<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
				<!--End user dropdown-->
				<li>
					<a href="javascript:void(-1)" class="aside-toggle navbar-aside-icon">
						<i class="pci-ver-dots"></i>
					</a>
				</li>
			</ul>
		</div>
		<!--================================-->
		<!--End Navbar Dropdown-->
	</div>
</header>
</template>

<script>
export default {
  name: "app-header"
  //   computed: {}
};
</script>

// src/main/webapp/entries/templates/nifty/react-files/web/app/components/layout/Header.js
import React, { Component } from "react";

const Header = () => {
    return (
        <header id="navbar">
            <div id="navbar-container" className="boxed">
                <div className="navbar-header">
                    <a href="/change-me" className="navbar-brand no-print">
                        <img src="images/logo.png" alt="Nifty Logo" className="brand-icon" />
                        <div className="brand-title">
                            <span className="brand-text">React Admin</span>
                        </div>
                    </a>
                </div>
                <div className="navbar-content clearfix no-print">
                    <ul className="nav navbar-top-links pull-left">
                        <li className="tgl-menu-btn">
                            <a href="/change-me" className="mainnav-toggle" >
                                <i className="fa demo-pli-view-list" />
                            </a>
                        </li>
                        <li className="mega-dropdown">
                            <a href="/change-me" className="mega-dropdown-toggle">
                                <i className="demo-pli-layout-grid" />
                            </a>
                            <div className="dropdown-menu mega-dropdown-menu" />
                        </li>
                    </ul>
                    <span className="main-header" />
                    <ul className="nav navbar-top-links pull-right">

                        <li id="dropdown-user" className="dropdown">
                            <a href="/change-me" data-toggle="dropdown" className="dropdown-toggle text-right">
                                <span className="pull-right">
                                    <i className="fa fa-user-o ic-user" />
                                </span>
                                <div className="index-username hidden-xs">chico</div>
                            </a>
                            <div className="dropdown-menu dropdown-menu-md dropdown-menu-right panel-default">
                                <br />
                                <ul className="head-list">
                                    <li>
                                        <a href="/profile">
                                            <i className="fa fa-user-o icon-lg icon-fw" />
                                            Meus Dados
                                        </a>
                                    </li>
                                    <li>
                                        <a href="/help">
                                            <i className="fa fa-info-circle icon-lg icon-fw" />
                                            Ajuda
                                        </a>
                                    </li>
                                </ul>
                                <div className="pad-all text-right">
                                    <a href="/logout" className="btn btn-primary">
                                        <i className="fa fa-sign-out" />
                                        Sair
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <a href="/change-me" className="aside-toggle navbar-aside-icon">
                                <i className="pci-ver-dots" />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
    )
}

export default Header;
