// src/main/webapp/entries/templates/nifty/vue-files/web/src/components/layout/Sidebar.vue
<template>
<nav id="mainnav-container" class="sidebar" >
	<div id="mainnav">
		<!--Menu-->
		<div id="mainnav-menu-wrap">
			<div class="nano">
				<div class="nano-content">
					<div id="mainnav-profile" class="mainnav-profile" style="padding: 30px 20px 12px; background-image: url('assets/images/nav-profile.png'); background-repeat: no-repeat; background-size: cover;">
						<div class="profile-wrap">
							<div class="pad-btm text-center">
								<img class="img-circle img-sm img-border" src="/static/images/no_photo.jpg" alt="Imagem usuário">
							</div>
							<a href="javascript:void(-1)" class="box-block" data-toggle="collapse" aria-expanded="false">
								<p class="mnp-name">chico</p>
								<span class="mnp-desc">chico@gmail.com</span>
							</a>
						</div>
					</div>
					<ul id="mainnav-menu" class="list-group">
						<li class="list-divider"></li>
						<li class="list-header">Acesso Rápido</li>
						<li>
							<a href="#app/dashboards">
								<i class="fa fa-line-chart"></i>
								<span class="menu-title">Dashboard</span>
							</a>
						</li>
						<li class="list-divider"></li>
						<li>
							<a href="javascript:void(-1)">
								<i class="fa fa-table"></i>
								<span class="menu-title">Cadastros</span>
								<i class="arrow"></i>
							</a>
							<!--Submenu-->
							<ul class="">
								<li id="filmes">
									<router-link to="/filmes/list">Novo Filme</router-link>
								</li>
							</ul>
						</li>
						<li class="list-divider"></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>
</template>

<script>
export default {
  name: "app-sidebar"
};
</script>

// src/main/webapp/entries/templates/nifty/react-files/web/app/components/layout/Sidebar.js
import React from "react";
import { HashRouter as Router, NavLink } from "react-router-dom";

export default class Sidebar extends React.Component {
    render() {
        return (
            <Router>
                <nav id="mainnav-container" className="sidebar" >
                    <div id="mainnav">
                        <div id="mainnav-menu-wrap">
                            <div className="nano">
                                <div className="nano-content">
                                    <div id="mainnav-profile" className="mainnav-profile">
                                        <div className="profile-wrap text-center">
                                            <div className="pad-btm">
                                                <img className="img-circle img-md" src="images/no_photo.jpg" alt="Profile " />
                                            </div>
                                            <a href="#profile-nav" className="box-block" data-toggle="collapse" aria-expanded="false">
                                                <p className="mnp-name">System Admin</p>
                                                <span className="mnp-desc">contato@jsetup.com</span>
                                            </a>
                                        </div>
                                    </div>
                                    <ul id="mainnav-menu" className="list-group">
                                        <li className="list-divider" />
                                        <li className="list-header">Acesso Rápido</li>
                                        <li>
                                            <a href="/dashboards">
                                                <i className="fa fa-line-chart" />
                                                <span className="menu-title">Dashboard</span>
                                            </a>
                                        </li>
                                        <li className="list-divider" />
                                        <li>
                                            <a href="/change-me">
                                                <i className="fa fa-table" />
                                                <span className="menu-title">Cadastros</span>
                                                <i className="arrow" />
                                            </a>
                                            <ul className="">
                                                <li id="newFilme">
                                                    <NavLink to="/filmes/new"> Novo Filme </NavLink>
                                                </li>
                                                <li id="filmes">
                                                    <NavLink to="/filmes/list"> Pesquisa de Filme </NavLink>
                                                </li>
                                            </ul>
                                        </li>
                                        <li className="list-divider" />
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </Router>
        );
    }
}
