// src/main/webapp/entries/common-files/appbaseVue/static/lixo/layout/components/sidebar/sidebar.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  //    styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent {
  isActive: boolean = false;
  showMenu: string = '';
  noPhotoImage: String = "./images/no_photo.jpg";
  eventCalled() {
    this.isActive = !this.isActive;
  }

  addExpandClass(element: any) {
    console.log('expand: ' + element);
    if (element === this.showMenu) {
      this.showMenu = '0';
    } else {
      this.showMenu = element;
    }
  }
}

<nav id="mainnav-container" class="sidebar" ngClass="{sidebarPushRight: isActive}">
	<div id="mainnav">
		<!--Menu-->
		<div id="mainnav-menu-wrap">
			<div class="nano">
				<div class="nano-content">
					<div id="mainnav-profile" class="mainnav-profile" style="padding: 30px 20px 12px; background-image: url('assets/images/nav-profile.png'); background-repeat: no-repeat; background-size: cover;">
						<div class="profile-wrap">
							<div class="pad-btm text-center">
								<img class="img-circle img-sm img-border" src="assets/images/no_photo.jpg" alt="Imagem usuário">
							</div>
							<a href="javascript:void(-1)" class="box-block" data-toggle="collapse" aria-expanded="false">
								<p class="mnp-name">chico</p>
								<span class="mnp-desc">chico@gmail.com</span>
							</a>
						</div>
					</div>
					<ul id="mainnav-menu" class="list-group">
						<li class="list-divider"></li>
						<li class="list-header">Acesso Rápido</li>
						<li>
							<a href="#app/dashboards">
								<i class="fa fa-line-chart"></i>
								<span class="menu-title">Dashboard</span>
							</a>
						</li>
						<li class="list-divider"></li>
						<li>
							<a href="javascript:void(-1)">
								<i class="fa fa-table"></i>
								<span class="menu-title">Cadastros</span>
								<i class="arrow"></i>
							</a>
							<!--Submenu-->
							<ul class="collapse">
								<li id="filmes">
									<router-link to="/filmes/new">Novo Filme</router-link>
								</li>
							</ul>
						</li>
						<li class="list-divider"></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>

// src/main/webapp/entries/templates/nifty/vue-files/web/src/components/layout/Sidebar.vue
<template>
<nav id="mainnav-container" class="sidebar" >
	<div id="mainnav">
		<!--Menu-->
		<div id="mainnav-menu-wrap">
			<div class="nano">
				<div class="nano-content">
					<div id="mainnav-profile" class="mainnav-profile" style="padding: 30px 20px 12px; background-image: url('assets/images/nav-profile.png'); background-repeat: no-repeat; background-size: cover;">
						<div class="profile-wrap">
							<div class="pad-btm text-center">
								<img class="img-circle img-sm img-border" src="/static/images/no_photo.jpg" alt="Imagem usuário">
							</div>
							<a href="javascript:void(-1)" class="box-block" data-toggle="collapse" aria-expanded="false">
								<p class="mnp-name">chico</p>
								<span class="mnp-desc">chico@gmail.com</span>
							</a>
						</div>
					</div>
					<ul id="mainnav-menu" class="list-group">
						<li class="list-divider"></li>
						<li class="list-header">Acesso Rápido</li>
						<li>
							<a href="#app/dashboards">
								<i class="fa fa-line-chart"></i>
								<span class="menu-title">Dashboard</span>
							</a>
						</li>
						<li class="list-divider"></li>
						<li>
							<a href="javascript:void(-1)">
								<i class="fa fa-table"></i>
								<span class="menu-title">Cadastros</span>
								<i class="arrow"></i>
							</a>
							<!--Submenu-->
							<ul class="">
								<li id="filmes">
									<router-link to="/filmes/list">Novo Filme</router-link>
								</li>
							</ul>
						</li>
						<li class="list-divider"></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>
</template>

<script>
export default {
  name: "app-sidebar"
};
</script>
