// src/main/webapp/entries/common-files/appbaseVue/src/components/filme/PageFilme.vue
<template>
<div >
	<div class="panel">
		<div class="panel-heading">
			<h3 class="panel-title">
				<i class="fa fa-search"></i>
				Pesquisa de Filme.
			</h3>
		</div>
		<div class="panel-body">
			<div id="messages_div"></div>
			<form id="formFilmeFilter">
				<div class="widget-main ">
					<div class="row pad-hor-7">
						<div class="col-xs-6">
							<a @click="create" class="btn btn-info">
								<i class="fa fa-plus-circle"></i>
								Novo Registro
							</a>
							&nbsp;
							<a @click="reset" class="btn btn-default ">Limpar</a>
						</div>
						<div class="col-sm-6">
							<div class="input-group">
								<input  type="text" v-model="datatableConfig.filterParameters.tituloOriginal" class=" form-control" placeholder="Pesquisar Filme por Título Original">
								<span id="query" class="input-group-btn ">
									<button type="button"  @click="paginate()" class="btn btn-default" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Pesquisando...">
										<span class="fa fa-search icon-on-right  "></span>
										Pesquisar
									</button>
								</span>
							</div>
							<div>
								<a @click="showAdvanceSearch = !showAdvanceSearch" > Pesquisa avançada... </a>
							</div>
						</div>
					</div>
				<collapse v-model="showAdvanceSearch">
					<div class="panel" >
							<div class="panel-heading">
								<h5 class="panel-title">Filtros avançados</h5>
							</div>
							<div class="panel-body">
								<!-- inicio dos registros-->
								<div id="groupInputTituloOriginal" class="form-group   ">
									<label class="control-label" for="inputTituloOriginal">Título</label>
									<input type="text" v-model="datatableConfig.filterParameters.tituloOriginal" placeholder="Pesquise pelo Título" class="form-control">
								</div>
								<div>
									<button type="button" @click="paginate()"  class="btn btn-info btn-sm search-button loading-button" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Pesquisando...">
										<i class="fa fa-search"></i>
										Pesquisar
									</button>
								</div>
							</div>
						</div>
				</collapse>
				</div>
			</form>
			<div class="center">
				<div class="">
					<div class="">
						<i v-if="!datatableConfig.loading" class="fa fa-align-justify"></i>
						<i v-if="datatableConfig.loading" class="fa fa-spinner fa-spin fa-fw"></i>
						Resultado da pesquisa
					</div>
					<table class="table table-striped table-bordered table-hover  no-footer  ">
						<thead>
							<tr>
								<th class="renderable nome">
									<a >
										<i class="fa" aria-hidden="true"></i>
										Titulo Original
									</a>
								</th>
								<th class="renderable descricao">
									<a >
										<i class="fa" aria-hidden="true"></i>
										Diretor
									</a>
								</th>
								<th class="renderable action-cell">Ações</th>
							</tr>
						</thead>
						<tbody>
							<tr v-for="filme in datatableConfig.items " :key="filme.id">
								<td>{{filme.tituloOriginal}}</td>
								<td>{{filme.diretor}}</td>
								<td class="td-actions action-butons-cell">
									<a href="javascript:void(-1)" class="btn btn-xs  btn-primary " @click="editFilme(filme)" data-toggle="tooltip" data-placement="top" title="" data-original-title="Editar Filme">
										<i class="fa fa-pencil fa-lg"></i>
									</a>
									<a href="javascript:void(-1)" class="btn btn-xs btn-danger " @click="removeFilme(filme)" data-toggle="tooltip" data-placement="top" title="" data-original-title="Remover Filme">
										<i class="fa fa-trash fa-lg"></i>
									</a>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="">
					<div class="col-md-6" style="text-align: left; margin: 15px 0">
						<div class=" float-left ">
							<span v-if="datatableConfig.loading" class="loading-elements">
								<span class="">
									<i v-if="datatableConfig.loading" class="fa fa-spinner fa-spin fa-fw"></i>
									Carregando...
								</span>
							</span>
							<span v-if="!datatableConfig.loading" class="has-elements" style="display: inline;">
								Registros
								<span class="initial-page">{{datatableConfig.first}}</span>
								a
								<span class="final-page">{{datatableConfig.last}}</span>
								de
								<span class="total-records">{{datatableConfig.totalRecords}}</span>
								. Exibindo até
								<select class="combo-page-size" v-on:change="paginate()" v-model="datatableConfig.pageSize"  style="padding: 0 0 0 0; height: 20px">
									<option value="3">3</option>
									<option value="5">5</option>
									<option value="10" >10</option>
									<option value="25">25</option>
									<option value="50">50</option>
								</select>
								por página.
							</span>
						</div>
					</div>
					<div class="">
					    <pagination v-model="datatableConfig.page" v-on:change="paginate" :total-page="datatableConfig.totalPages" align="right" />
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

</template>
<script>
import DatatableConfig from "@/components/core/DatatableConfig";
import HttpRequest from "@/components/core/HttpRequest";

export default {
  created: function() {
    this.service = new HttpRequest("/rs/crud/filmes");
  },

  mounted: function() {
    this.paginate();
  },

  data: function() {
    return {
      showAdvanceSearch: false,
      datatableConfig: new DatatableConfig()
    };
  },

  methods: {
    create: function() {
      this.$router.push({ path: "/filmes/new/" });
    },

    editFilme: function(_filme) {
      this.$router.push({ path: "/filmes/edit/" + _filme.id });
    },

    reset: function() {
      this.datatableConfig = new DatatableConfig();
    },

    removeFilme: function(_filme) {
      console.log("removeFilme" + _filme);
    },

    paginate: function(pageIndex = 1) {
      this.datatableConfig.page = pageIndex;

      this.service.getPage(
        this.datatableConfig,
        data => {
          console.log("success fetching page");
        },

        error => {
          console.error("error fetching page", error);
        }
      );
    }
  }
};
</script>

// src/main/webapp/entries/templates/nifty/react-files/web/app/components/filme/PageFilme.js
import React from "react"
import JSPagination from "../core/JSTablePagination"
import DatatableConfig from "../core/DatatableConfig"
import HttpRequest from "../core/HttpRequest"

export default class PageFilme extends React.Component {
    constructor(props) {
        super(props)
        this.service = new HttpRequest("/rs/crud/filmes");
        this.state = {
            datatableConfig: new DatatableConfig(),
            showFilter: false,
        }
    }
    componentDidMount = () => {
        this.paginate();
    }
    create = () => {
        // this.$router.push({ path: "/filmes/new/" });
    }

    editFilme = (_filme) => {
        // this.$router.push({ path: "/filmes/edit/" + _filme.id });
        console.log("editando filme ", _filme);
    }

    reset = () => {
    }

    // será que é necessário usar o state??
    changePageSize = (event) => {
        const target = event.target;
        const theDatatableConfig = Object.assign(new DatatableConfig(), this.state.datatableConfig)
        theDatatableConfig.pageSize = parseInt(target.value, 10);
        theDatatableConfig.page = 1;

        // o estado do 
        this.setState({ datatableConfig: theDatatableConfig }, this.paginate);
    }

    removeFilme = (_filme) => {
        console.log("removendo filme ", _filme);
    }

    paginate = (pageIndex = 1) => {
        const stateConf = this.state.datatableConfig;
        const datatableConfig = Object.assign(new DatatableConfig(), this.state.datatableConfig)
        datatableConfig.page = pageIndex;
        datatableConfig.loading = true;

        this.setState({ datatableConfig });

        this.service.getPage(
            datatableConfig,
            data => {
                datatableConfig.loading = false;
                datatableConfig.totalRecords = data.totalRecords;
                this.setState({ datatableConfig });
            },

            error => {
                console.error("error fetching filme´s page", error);
            }
        );
    }

    changeSearchFormHandle = (event) => {
        /* Jogar essa atualização do state para fora, COMO?? */
        const target = event.target;
        const value = target.type === 'checkbox' ? target.checked : target.value;
        const name = target.name;

        const datatableConfig = { ...this.state.datatableConfig };
        datatableConfig.filterParameters[name] = value;

        this.setState({ datatableConfig });
    }
    showAdvancedSearchHandler = () => {
        console.log("Chamou o advanceSeach");
    }
    render = () => {
        return (
            <div >
                <div className="panel">
                    <div className="panel-heading">
                        <h3 className="panel-title">
                            <i className="fa fa-search" />
                            &nbsp;Pesquisa de Filme.
                        </h3>
                    </div>
                    <div className="panel-body">
                        <div id="messages_div" />
                        <form id="formFilmeFilter">
                            <div className="row">
                                <div className="page-toolbar">
                                    <div className="col-sm-6">
                                        <button type="button" onClick={this.create} className="btn btn-info">
                                            Novo Registro
                                        </button>
                                        <button className="btn btn-default ">Limpar</button>
                                        <button type="button" className="btn btn-default" onClick={() => this.setState({ showFilter: !this.state.showFilter })}  > Pesquisa avançada... </button>
                                    </div>
                                    <div className="col-sm-6">
                                        <div className="input-group">
                                            <input type="text" value={this.state.datatableConfig.filterParameters.tituloOriginal} className=" form-control" placeholder="Pesquisar Filme por Título Original" />
                                            <span id="query" className="input-group-btn ">
                                                <button type="button" onClick={(event) => this.paginate()} className="btn btn-default" >
                                                    Pesquisar
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="panel" style={{ display: this.state.showFilter ? "block" : "none" }} >
                                <div className="panel-heading">
                                    <h5 className="panel-title">Filtros avançados</h5>
                                </div>
                                <div className="panel-body">
                                    <div className="form-group">
                                        <label className="control-label" htmlFor="tituloOriginal">Título Original</label>
                                        <input type="text" name="tituloOriginal" onChange={this.changeSearchFormHandle} value={this.state.datatableConfig.filterParameters.tituloOriginal} className="form-control" />
                                    </div>
                                    <div className="form-group">
                                        <label className="control-label" htmlFor="duracao">Duração</label>
                                        <input type="text" name="duracao" value={this.state.datatableConfig.filterParameters.duracao} className="form-control" />
                                    </div>

                                    <div className="form-group">
                                        <label className="control-label" htmlFor="sinopse">Sinopse</label>
                                        <textarea rows="3" model={this.state.datatableConfig.filterParameters.sinopse} className="form-control" maxLength="2000" />
                                    </div>
                                    <div className="form-group">
                                        <label className="control-label" htmlFor="titulo">Título</label>
                                        <input type="text" name="titulo" value={this.state.datatableConfig.filterParameters.titulo} className="form-control" />
                                    </div>
                                    <div className="form-group">
                                        <label className="control-label" htmlFor="diretor">Diretor</label>
                                        <input type="text" name="diretor" value={this.state.datatableConfig.filterParameters.diretor} className="form-control" />
                                    </div>

                                    <div id="groupInputTituloOriginal" className="form-group   ">
                                        <label className="control-label" htmlFor="inputTituloOriginal">Título</label>
                                        <input type="text" value={this.state.datatableConfig.filterParameters.tituloOriginal} placeholder="Pesquise pelo Título" className="form-control" />
                                    </div>
                                    <div>
                                        <button type="button" onClick={(event) => this.paginate()} className="btn btn-info btn-sm search-button loading-button" >
                                            <i className="fa fa-search" />
                                            &nbsp;Pesquisar
                                            </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div className="cente">
                            <div className="table-responsive ">
                                <div className="">
                                    <i className="fa fa-align-justify" />
                                    &nbsp;Resultado da pesquisa
                                </div>
                                <table className="table table-striped table-bordered table-hover dataTable no-footer">
                                    <thead>
                                        <tr>
                                            <th className="th-tituloOriginal">
                                                <a >
                                                    <i className="fa " />
                                                    Título Original
                                                </a>
                                            </th>
                                            <th className="th-poster">
                                                <a >
                                                    <i className="fa " />
                                                    Poster
                                                </a>
                                            </th>
                                            <th className="th-duracao">
                                                <a >
                                                    <i className="fa " />
                                                    Duração
                                                </a>
                                            </th>
                                            <th className="th-dataLancamento">
                                                <a >
                                                    <i className="fa " />
                                                    Data do Lançamento
                                                </a>
                                            </th>
                                            <th className="th-sinopse">
                                                <a >
                                                    <i className="fa " />
                                                    Sinopse
                                                </a>
                                            </th>
                                            <th className="th-titulo">
                                                <a >
                                                    <i className="fa " />
                                                    Título
                                                </a>
                                            </th>
                                            <th className="th-diretor">
                                                <a >
                                                    <i className="fa " />
                                                    Diretor
									            </a>
                                            </th>
                                            <th className="th-linguagem">
                                                <a >
                                                    <i className="fa " />
                                                    Linguagem
									            </a>
                                            </th>
                                            <th className="th-classificacao">
                                                <a >
                                                    <i className="fa " />
                                                    Classificação
									            </a>
                                            </th>
                                            <th className="td-actions"> Ações </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {
                                            this.state.datatableConfig.items.map((filme, index) => {
                                                return (
                                                    <tr key={filme.id}>
                                                        <td>{filme.tituloOriginal}</td>
                                                        <td>{filme.poster}</td>
                                                        <td>{filme.duracao}</td>
                                                        <td>{filme.dataLancamento}</td>
                                                        <td>{filme.sinopse}</td>
                                                        <td>{filme.titulo}</td>
                                                        <td>{filme.diretor}</td>
                                                        <td>{filme.linguagem && filme.linguagem.nome}</td>
                                                        <td>{filme.classificacao && filme.classificacao.nome}</td>
                                                        <td className="td-actions action-butons-cell">
                                                            <button className="btn btn-xs  btn-primary " onClick={(event) => this.editFilme(filme)} data-toggle="tooltip" data-placement="top" title="" data-original-title="Editar Filme">
                                                                <i className="fa fa-pencil fa-lg" />
                                                            </button>

                                                            <button className="btn btn-xs btn-danger " onClick={(event) => this.removeFilme(filme)} data-toggle="tooltip" data-placement="top" title="" data-original-title="Remover Filme">
                                                                <i className="fa fa-trash fa-lg" />
                                                            </button>
                                                        </td>
                                                    </tr>
                                                )
                                            })
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <div className="row page-footer-components">
                                <div className="col-md-6" >
                                    <div className=" float-left ">
                                        {this.state.datatableConfig.loading ?
                                            <span className="loading-elements">
                                                <span className="">
                                                    <i className="fa fa-spinner fa-spin fa-fw" />
                                                    Carregando...
								            </span>
                                            </span>
                                            :
                                            <span className="has-elements" >
                                                Registros
								                <span className="initial-page">&nbsp;{this.state.datatableConfig.first}&nbsp;</span>
                                                a
								                <span className="final-page">&nbsp;{this.state.datatableConfig.last}&nbsp;</span>
                                                de
								                <span className="total-records">&nbsp;{this.state.datatableConfig.totalRecords}</span>
                                                . Exibindo até
								                <select className="combo-page-size" onChange={this.changePageSize} value={this.state.datatableConfig.pageSize}>
                                                    <option value="3">3</option>
                                                    <option value="5">5</option>
                                                    <option value="10" >10</option>
                                                    <option value="25">25</option>
                                                    <option value="50">50</option>
                                                </select>
                                                por página.
							                </span>
                                        }
                                    </div>
                                </div>
                                <div className="col-md-6" >
                                    <div className="pull-right" >
                                        <JSPagination onPaginate={this.paginate} totalItems={this.state.datatableConfig.totalRecords} page={this.state.datatableConfig.page} pageSize={this.state.datatableConfig.pageSize} />
                                    </div>
                                </div >
                            </div >
                        </div >
                    </div >
                </div >
            </div >
        );
    }
}
